// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_udt3JpiFe_v9e-Ce9P4A1ia2UvuufOw',
    appId: '1:804048152258:web:3350abdc02f7713dc2fd5b',
    messagingSenderId: '804048152258',
    projectId: 'fixit-oman',
    authDomain: 'fixit-oman.firebaseapp.com',
    storageBucket: 'fixit-oman.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_udt3JpiFe_v9e-Ce9P4A1ia2UvuufOw',
    appId: '1:804048152258:android:3350abdc02f7713dc2fd5b',
    messagingSenderId: '804048152258',
    projectId: 'fixit-oman',
    storageBucket: 'fixit-oman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_udt3JpiFe_v9e-Ce9P4A1ia2UvuufOw',
    appId: '1:804048152258:ios:3350abdc02f7713dc2fd5b',
    messagingSenderId: '804048152258',
    projectId: 'fixit-oman',
    storageBucket: 'fixit-oman.firebasestorage.app',
    iosBundleId: 'com.fixit.oman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_udt3JpiFe_v9e-Ce9P4A1ia2UvuufOw',
    appId: '1:804048152258:macos:3350abdc02f7713dc2fd5b',
    messagingSenderId: '804048152258',
    projectId: 'fixit-oman',
    storageBucket: 'fixit-oman.firebasestorage.app',
    iosBundleId: 'com.fixit.oman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_udt3JpiFe_v9e-Ce9P4A1ia2UvuufOw',
    appId: '1:804048152258:windows:3350abdc02f7713dc2fd5b',
    messagingSenderId: '804048152258',
    projectId: 'fixit-oman',
    storageBucket: 'fixit-oman.firebasestorage.app',
  );
}